server:
  port: 5555
spring:
  application:
    name: test-server



eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
    response-cache-update-interval-ms: 2000
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
       defaultZone: http://127.0.0.1:5555/eureka
